services:
  nginx:
    build: requirements/nginx
    image: nginx:inception
    container_name: nginx
    ports:
      - "8443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - hb-net
    depends_on:
      - wordpress
    restart: unless-stopped

  mariadb:
    build: requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - ROOT_PASS=${ROOT_PASS}
    networks:
      - hb-net
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DOMAIN=${DOMAIN}

    networks:
      - hb-net
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  wordpress_data:
    name: wordpress_data
    driver_opts:
      type: bind
      o: bind
      device: /home/hboudar/data/wordpress
  mariadb_data:
    name: mariadb_data
    driver_opts:
      type: bind
      o: bind
      device: /home/hboudar/data/mariadb

networks:
  hb-net:
    driver: bridge