services:
  nginx:
    build: requirements/nginx
    image: nginx:inception
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8443:443"
    networks:
      - my-net
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

  mariadb:
    build: requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    restart: unless-stopped
    networks:
      - my-net
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - db_pass
      - root_pass

  wordpress:
    build: requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    restart: unless-stopped
    networks:
      - my-net
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DOMAIN=${DOMAIN}
      - TITLE=${TITLE}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - USER_NAME=${USER_NAME}
      - USER_EMAIL=${USER_EMAIL}
      - REDIS_HOST=${REDIS_HOST}
    secrets:
      - db_pass
      - admin_pass
      - user_pass
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

  # bonus part
  adminer:
    build: requirements/bonus/adminer
    image: adminer:inception
    container_name: adminer
    restart: unless-stopped
    networks:
      - my-net
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    build: ./requirements/bonus/Redis
    container_name: redis
    restart: always
    expose:
      - "6379"
    networks:
      - my-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  ftp:
    build: ./requirements/bonus/FTP
    container_name: ftp
    restart: always
    ports:
      - "2121:2121"
      - "30000-30100:30000-30100"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - FTP_USER=ftpuser
    secrets:
      - ftp_pass
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "2121"]
      interval: 10s
      timeout: 5s
      retries: 3





volumes:
  wordpress_data:
    name: wordpress_data
    driver_opts:
      type: bind
      o: bind
      device: /home/hboudar/data/wordpress
  mariadb_data:
    name: mariadb_data
    driver_opts:
      type: bind
      o: bind
      device: /home/hboudar/data/mariadb

networks:
  my-net:
    driver: bridge

secrets:
  db_pass:
    file: ./../secrets/db_pass.txt
  admin_pass:
    file: ./../secrets/admin_pass.txt
  user_pass:
    file: ./../secrets/user_pass.txt
  root_pass:
    file: ./../secrets/root_pass.txt
  ftp_pass:
    file: ./../secrets/ftp_pass.txt
