services:
  nginx:
    build: requirements/nginx
    image: nginx:inception
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8443:443"
    networks:
      - my-net
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

  mariadb:
    build: requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    restart: unless-stopped
    networks:
      - my-net
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - ROOT_PASS=${ROOT_PASS}

  wordpress:
    build: requirements/wordpress
    image: wordpress:inception
    container_name: wp-php
    restart: unless-stopped
    networks:
      - my-net
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - ADMIN_PASS=${ADMIN_PASS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - USER_NAME=${USER_NAME}
      - USER_PASS=${USER_PASS}
      - USER_EMAIL=${USER_EMAIL}
    depends_on:
      - mariadb

volumes:
  wordpress_data:
    name: wordpress_data
    driver_opts:
      type: bind
      o: bind
      device: /home/hboudar/data/wordpress
  mariadb_data:
    name: mariadb_data
    driver_opts:
      type: bind
      o: bind
      device: /home/hboudar/data/mariadb

networks:
  my-net:
    driver: bridge